### PR TITLE
Upgraded metadata ui to GTK3

### PR DESCRIPTION
**Pull request by maruiz93**
I have also changed ComboBoxEntryExt to a ComboBox without entry.
Now, series field is no writeable, but only selectable.

### CODE REVIEW

**Comment by sinhote** [comment]
I would say you will need to work on this later. The series field not being writable means that you will have to deal with a HUGE list of series if you have a medium-sized Opencast installation, making a plain drop-down menu very difficult to use. 

According to what I see [here](http://python-gtk-3-tutorial.readthedocs.org/en/latest/combobox.html), it looks like the "entry" functionality has been included directly in the combobox class (take a look at the example).

Please consider to "upgrade" this change to provide the same mechanism as before, otherwise it will be really difficult to filter through a large amount of series.

**Comment by bleedinge** [comment]
I agree with @sinhote. It looks it will be hard to handle such a large list otherwise. It should be possible to  filter the series.

**Comment by sinhote** [comment]
Reviewing my comment before, I said something that is not true --the has been no structural changes (apparently) between GTK2 and 3. I worked with these menus in a functionality we developed for Helsinki, and they are a real pain because they use a very theoretical model to store the data, not programmer-friendly at all.

So the thing is you have a `ComboBox` and you can set it up so that it has an `Entry` within. This part is easy and is described in the link I mentioned above. The problem is:

1. There is no assumption that whatever you type in the box must exist in the `ComboBox`. In other words, if you have a menu with two options "orange" and "blue", the `ComboBox` does not prevent you, by default, from writing "red" in the text entry and get away with it. In my implementation for Helsinki, the user is allowed to type whatever they want, but when the entry value is set (by clicking enter or releasing the focus), the text is compared against the whole list displayed in the drop-down menu and, if a match is found, the corresponding row is selected, otherwise (I don't remember quite well), the text value is set to the previous valid value or the entry is simply not validated. 
2. When you are typing a value, no suggestions are displayed. You need to use a `EntryCompletion` on the internal Entry of the `ComboBox`. The `EntryCompletion` needs a data tree with the possible options to match with, so you need to use the same data tree for the `ComboBox` itself AND the `EntryCompletion`. 

It gets really messy really quick, as you can see, and I do not remember some of the tiny implementation details that made it even more confusing. However, I think I got it done pretty well in the community version and should not be hard to get it working in GTK3 --the changes do not seem too big. Please let me know if you need us to take a closer look.

**Comment by sinhote** [comment]
And a final comment (I promise this is the last one :P): it is OK if you consider that the class `ComboBoxEntryExt` is superfluous. Maybe it is. You can keep the same functionality with a normal, properly configured `ComboBox`. You just need to instantiate it with an `Entry` (there's a function for that) and set up all the callbacks correctly. Essentialy, what was done inside the `ComboBoxEntryExt`, but without creating a new class.

**Comment by maruiz93** [comment]
I close this pull-request because I've opened [this one](https://github.com/teltek/Galicaster/pull/148) keeping the filtering feature of the Combobox.

**Pull request closed without merging**
