### PR TITLE
Manchester QRcode Plugin

### PR DESCRIPTION
**Pull request by androidwiltron**
Galicaster 2 compatible QRcode plugin
see docs/plugins/qrcode/readme.txt
## galicaster conf.ini:

[plugins]
qrcode = True

True: Enables plugin.
False: Disables plugin.
## Plugin Options

[qrcode]
pause_mode = hold
hold_code = pause
stop_code = stop
start_code = start
rescale = 640x360
mp_add_edits = False
mp_force_trimhold = False
mp_add_smil = False
drop_frames = True
buffers = 200
hold_timeout = 1
ignore_track_name = trackname1,trackname2

### CODE REVIEW

**Comment by Alfro** [comment]
Hello Manchester!

We are very glad you are contributing your QR plugin to the Galicaster project! We are very excited about this and we are looking forward to the community making more contributions and new plugins in the future.

As you already know, starting with Galicaster 2.0, we are emphasizing a more modular approach, adding functionality through plugins and extensions. We also want these plugins to have a more dynamic development, not having to depend on each next pending Galicaster release, and at the same time to give the developers of the plugin more leeway to work on their plugins, whether it's adding changes or fixing bugs.

Given all this, we think it makes more sense to separate new plugins into their own repositories. The first example of this is the camera control plugin we recently developed for Galicaster: 
https://github.com/teltek/Galicaster-plugin-cameracontrol
We would like to do the same with your new contribution. We have already created a separated repository for your plugin with the required structure here:
https://github.com/teltek/Galicaster-plugin-qrcode
We would really appreciate it if you could do a pull request against that repository instead.

Thanks again for your contribution! If you have any doubts, don't hesitate to ask.

Best Regards,

**Comment by androidwiltron** [comment]
Hi,

thanks. yeah that sounds fine however to get QR code functioning i need a function in the galicaster recorder.py, have a look at the pull request. should i do a separate pull request for this part?

**Comment by Alfro** [comment]
@androidwiltron Sure. That would be great.

**Comment by Alfro** [comment]
Hi @androidwiltron 
Did you have any issues with pulling the qr plugin to the other project? If you prefer I can create the PRs myself.

**Comment by androidwiltron** [comment]
Hi. sorry, other tickets got in the way. i'll prioritise this and get it
sorted. thanks

**Comment by androidwiltron** [comment]
closing pull request. plugin will exist in its own repo. see here: https://github.com/teltek/Galicaster-plugin-qrcode/pull/1

**Comment by Alfro** [comment]
@androidwiltron Don't forget about `get_recording_start_time` :)

**Pull request closed without merging**
