### PR TITLE
fix for nightly timer and error handling sending recorder status to opencast

### PR DESCRIPTION
**Pull request by androidwiltron**

### CODE REVIEW

**Comment by sinhote** [comment]
You should never, ever, ever use multithreading with pyGTK: https://wiki.gnome.org/Projects/PyGObject/Threading

You are kind of forced to use the threading facilities provided by GTK, which ensure the "threads" are handled within GTK's mainloop. Otherwise, segment faults will start randomly appearing on the long (or short) run.

**Comment by androidwiltron** [comment]
AH ok , noted, thanks. I may need to look more but i cant find a way in pyGTK to do this?

**Comment by Alfro** [comment]
Hi!
You should be able to do it by making the `__notify_timer_daily` function return `False` instead of `True` and calling `GObject.timeout_add_seconds()` inside it like you do with the `Timer.start()`.

I would also prefer if you do a separate PR for each fix (nightly and recorder status).

Cheers!

**Comment by androidwiltron** [comment]
closed based on threading issue raised by ruben

**Pull request closed without merging**
