### PR TITLE
improve plugin loading logging

### PR DESCRIPTION
**Pull request by ppettit**
just a small patch that changes no functionality, but i found it useful when writing plugins.

logs stack trace when something goes wrong inside the plugin
(very useful when developing). also logs whether the plugin is
internal or external when it loads, which helps understand which
version of a plugin is loading (if you have installed plugin with
pip as well as in the galicaster plugins directory for example).

### CODE REVIEW

**Comment by ppettit** [comment]
actually, just thinking maybe the plugin loader should actually try loading external plugins first, so that internal ones can be overridden? happy to change that if it is a good idea.

**Comment by Alfro** [comment]
Seems okay. Thanks!

**Comment by Alfro** [comment]
I am not sure about overriding internal plugins with external ones though. What would the advantage be of overriding internal plugins vs directly modifying their code?

**Comment by ppettit** [comment]
thought maybe it would be easier to install an updated or modified version of a plugin that is part of galicaster. but actually i guess you could just make a copy and rename it if needed.

was just a thought but i think you are right it is not necessary!

thanks!

**Pull request merged**
