### PR TITLE
css to fix inverted vu meter in ubuntu 18.04

### LINKED ISSUE #618: Invert Galicaster audio meter on Ubuntu18
On Ubuntu 16, the audio levels are green and mover from left to right:

Ubuntu16

On Ubuntu 18, the audio levels are orange and move from right to left.

Ubuntu18

This can be confusing to users. The audio levels should move from left to right as it did in Ubuntu 16.

### PR DESCRIPTION
**Pull request by ppettit**
fixes #618

### CODE REVIEW

**Comment by androidwiltron** [comment]
@ppettit this looks good except i think it should be a pull against `master` unless im incorrect

**Comment by ppettit** [comment]
@androidwiltron well it is a bug fix so i thought it should go into the release branch?

**Comment by androidwiltron** [comment]
@ppettit ha, i'm tired, let me review the rules sorry

**Comment by androidwiltron** [comment]
https://github.com/teltek/Galicaster-doc/blob/master/DeveloperGuide/ReviewingRules.md

ok so features must go `master` nothing explicit on bugs so i'll undo what i did, sorry for the confustion @ppettit

**Comment by ppettit** [comment]
@androidwiltron cool no problem! i was going by [CONTRIBUTING.md](https://github.com/teltek/Galicaster/blob/master/CONTRIBUTING.md) which says "All bugfixes should be contributed to the first affected release branch."

I know technically earlier releases are also affected but I assume we aren't likely to release anything further back.

**Comment by Alfro** [comment]
Thanks guys!

**Pull request merged**
