### PR TITLE
Correct the improper uses of the word "temporal" throughout the code

### PR DESCRIPTION
**Pull request by sinhote**
I found some log statements in Galicaster that were using the word "temporal" incorrectly. Then I checked the code and I saw that there were some more (not so visible) instances of the same mistake, so I've fixed them all.

In English, the opposite of "permanent" is not "temporal", but "temporary". The world "temporal" exists, but it means "of or relating to time" (as opposed to "space"). In Spanish, however, there are no such distinction.

Therefore, some instances of the word "temporal" in the code were correct (in the mediapackage, for instance, there are "temporal" metadata --i.e. they refer to the time the mediapackage was created--), while others were not (i.e. "*temporal files" or "*temporal folder" which should read "temporary files" and "temporary folder").

Not a big deal, but I figured out it was a good idea to correct the grammar!

### CODE REVIEW

**Comment by Alfro** [comment]
Thanks!
Finish fixing the tests and I will merge this into 2.0.x

**Comment by Alfro** [comment]
Ups, also, remove the conf.ini file. We don't want all galicasters to be called `GCMobile-sinho-laptop` by default :sweat_smile:

**Comment by sinhote** [comment]
Oops! I had local modifications and I mistakenly committed them :S 

Now everything should be OK

**Comment by Alfro** [comment]
Thanks!

**Pull request merged**
